spring:
  profiles:
    active: stress
---
spring:
  application:
    name: spring-mvc
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    com.study: debug
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
---
#??? ??? ??? ???? ?????
spring:
  config:
    activate:
      on-profile: stress
  datasource:
    url: jdbc:mariadb://localhost:3308/sample
    username: user
    password: 1234
# ??? ??? ??? ???? ??
