### 테스트 하는 법 포스트맨 없이
### 서버가 실행되야 테스트 가능
### create
POST {{domain}}/article
Content-Type: application/json

{
  "title": "title test success ?",
  "body": "body1",
  "authorId": 1234
}

### get
GET {{domain}}/article/8

### getAll
GET {{domain}}/article/all

### put
PUT {{domain}}/article/8
Content-Type: application/json

{
  "title": "title update",
  "body" : "body14",
  "authorId": 5467
}

### Delete
DELETE {{domain}}/article/11